name = "StrataDoc"
defaultTargets = ["docs"]

[[require]]
name = "verso"
git = "https://github.com/leanprover/verso"
rev = "nightly-testing"

[[lean_lib]]
name = "StrataDoc"

[[lean_exe]]
name = "docs"
root = "StrataDocMain"